### ISSUE TITLE
ERROR in xxx.js from UglifyJs Unexpected token: name (hook)

### ISSUE THREAD

**Issue by weigong12** [staticdeng/vuejs-loadmore#1]
When I use this component library, it runs normally local development, but an error is reported when using uglifyjs webpack plugin for webpack packaging.

The following is the detailed error reporting information:

`ERROR in js/vendors.bc580846f352f4ad3188.js from UglifyJs
Unexpected token: name (hook) [js/vendors.bc580846f352f4ad3188.js:56427,10]
Child extract-text-webpack-plugin ../../../node_modules/extract-text-webpack-plugin/dist ../../../node_modules/css-loader/index.js!../../../node_modules/postcss-loader/lib/index.js??ref--1-3!../../../node_modules/less-loader/dist/cjs.js!../stylesheets/application.less:`

**Comment by staticdeng** [comment]
This is the reason for the incompatibility：https://github.com/vuejs/rollup-plugin-vue/issues/262

I have solved this problem, please install version 1.0.1 to solve it
