### ISSUE TITLE
There are two props called 'loading-text'.

### ISSUE THREAD

**Issue by wealways** [staticdeng/vuejs-loadmore#2]
hi I have two questions :)

One is Refreshing, the other is Loading. 
I want to use the two separately.

and

Is there any way to turn off infinite scroll?

**Comment by staticdeng** [comment]
You can just not bind `on-loadmore` props to turn off infinite scroll.
Similarly, you can also not bind `on-refresh` props to turn off refresh.

**Comment by staticdeng** [comment]
There is an incorrect comment in readme. I have fixed it
