### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect

### ISSUE THREAD

**Issue by locdlocd** [staticdeng/vuejs-loadmore#6]
调用的时候为什么一直报这个错
"[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'getBoundingClientRect' of undefined"\n\nfound in\n\n---> <Loadmore>\n       <xxx> at src/xxx.vue\n         <App> at src/App.vue\n           <Root>"

**Comment by staticdeng** [comment]
是不是用的非移动端浏览器呢，getBoundingClientRect有兼容性，移动端的都支持

**Comment by llooooooo** [comment]
我也遇到了同样的问题，麻烦问一下你是如何解决的

**Comment by leafiy** [comment]
checkSroll没有解绑

`mounted () {
this._checkSroll = throttle(this.checkSroll, 200)

    this.scroller.addEventListener('scroll', this._checkSroll)
beforeDestroy () {
    this.scroller.removeEventListener('scroll', this._checkSroll)
  },`

**Comment by leafiy** [comment]
checkSroll没有解绑

`mounted () {
this._checkSroll = throttle(this.checkSroll, 200)

    this.scroller.addEventListener('scroll', this._checkSroll)
beforeDestroy () {
    this.scroller.removeEventListener('scroll', this._checkSroll)
  },`

**Comment by staticdeng** [comment]
> checkSroll没有解绑
> 
> `mounted () { this._checkSroll = throttle(this.checkSroll, 200)
> 
> ```
> this.scroller.addEventListener('scroll', this._checkSroll)
> ```
> 
> beforeDestroy () { this.scroller.removeEventListener('scroll', this._checkSroll) },`

谢谢你替我找到这个bug，我在下一个版本中马上解决

**Comment by staticdeng** [comment]
> 我也遇到了同样的问题，麻烦问一下你是如何解决的

This is a bug in a certain scenario. I have fixed this problem in v1.0.8
这是一个在某种场景下出现的bug,我已经在v1.0.8版本中修复了这个问题

**Comment by staticdeng** [comment]
> > 我也遇到了同样的问题，麻烦问一下你是如何解决的
> 
> This is a bug in a certain scenario. I have fixed this problem in v1.0.8 这是一个在某种场景下出现的bug,我已经在v1.0.8版本中修复了这个问题

**Comment by staticdeng** [comment]
This is a bug in a certain scenario. I have fixed this problem in v1.0.8
这是一个在某种场景下出现的bug,我已经在v1.0.8版本中修复了这个问题

**Comment by staticdeng** [comment]
> 调用的时候为什么一直报这个错 "[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'getBoundingClientRect' of undefined"\n\nfound in\n\n---> \n at src/xxx.vue\n at src/App.vue\n "

I updated v1.0.8 to fix this problem. Please update it to see if the problem has been solved
我更新了v1.0.8版本来修复这个问题，请更新一下看看问题解决了没有

**Comment by locdlocd** [comment]
thanks



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 23, 2022 14:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [staticdeng/vuejs-loadmore] TypeError: Cannot read property 'getBoundingClientRect (Issue #6)




  
调用的时候为什么一直报这个错 "[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'getBoundingClientRect' of undefined"\n\nfound in\n\n---&gt; \n at src/xxx.vue\n at src/App.vue\n "
  
I updated v1.0.8 to fix this problem. Please update it to see if the problem has been solved
 我更新了v1.0.8版本来修复这个问题，请更新一下看看问题解决了没有
