### ISSUE TITLE
In README, there have something wrong with the attribute name

### ISSUE THREAD

**Issue by zhang-jerry123** [staticdeng/vuejs-loadmore#7]
It should be `refresh-text` not `loading-text` 
<img width="800" alt="截屏2022-10-13 10 31 58" src="https://user-images.githubusercontent.com/65890681/195545151-2363e0fb-e320-4c42-93f2-398910cfea6a.png">

**Comment by staticdeng** [comment]
Tank You! There is an incorrect comment in readme. I have fixed it
